CREATE TABLE IF NOT EXISTS bugs (
    id SERIAL PRIMARY KEY,
    service VARCHAR(100) NOT NULL,
    method VARCHAR(100) NOT NULL,
    path VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    stack TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);